### PR TITLE
add github workflow that checks sdist installation

### PR DESCRIPTION
**Pull request by Jonathanlyj**

### CODE REVIEW

**Comment by wkliao** [comment]
Why not doing this in the 2 already existing yaml files?

**Comment by Jonathanlyj** [comment]
> Why not doing this in the 2 already existing yaml files?

If so we need to do pip uninstall pnetcdf first to refresh the env before re-installing with sdist. But pip uninstall doesn't clear the env entirely. I have seen the pip re-install is using some legacy metadata in  `*.egg-info` folder is used in combination with new MANIFEST.in file. It's safest to build and test in a new env

**Comment by wkliao** [comment]
Will running 'make install-clean' after 'pip uninstall'  be sufficient?
See Makefile.
https://github.com/Parallel-NetCDF/PnetCDF-Python/blob/4f1d279e45b2a154853c18cb871b57c1a732ca60/Makefile#L32-L33

**Comment by Jonathanlyj** [comment]
> Will running 'make install-clean' after 'pip uninstall' be sufficient? See Makefile.

It works. Just updated the pr

**Pull request merged**
